In [25]:
#Importing the Pandas and Numpy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Reading the CSV file

df = pd.read_csv('sonar_csv.csv')

In [3]:
df.head()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0       0.0200       0.0371       0.0428       0.0207       0.0954   
1       0.0453       0.0523       0.0843       0.0689       0.1183   
2       0.0262       0.0582       0.1099       0.1083       0.0974   
3       0.0100       0.0171       0.0623       0.0205       0.0205   
4       0.0762       0.0666       0.0481       0.0394       0.0590   

   attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0       0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1       0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2       0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3       0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4       0.0649       0.1209       0.2467       0.3564        0.4459  ...   

   attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0        0.0027        0.0065        0.0159        0.0072        0.0167   
1        0.0084        0.0089        0.0048        0.0094        0.0191   
2        0.0232        0.0166        0.0095        0.0180        0.0244   
3        0.0121        0.0036        0.0150        0.0085        0.0073   
4        0.0031        0.0054        0.0105        0.0110        0.0015   

   attribute_57  attribute_58  attribute_59  attribute_60  Class  
0        0.0180        0.0084        0.0090        0.0032   Rock  
1        0.0140        0.0049        0.0052        0.0044   Rock  
2        0.0316        0.0164        0.0095        0.0078   Rock  
3        0.0050        0.0044        0.0040        0.0117   Rock  
4        0.0072        0.0048        0.0107        0.0094   Rock  

[5 rows x 61 columns]

In [4]:
#Lets find out total rows and columns in our dataset
df.shape

(208, 61)

# Finding out whether we have any categorical or Null value column

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   attribute_1   208 non-null    float64
 1   attribute_2   208 non-null    float64
 2   attribute_3   208 non-null    float64
 3   attribute_4   208 non-null    float64
 4   attribute_5   208 non-null    float64
 5   attribute_6   208 non-null    float64
 6   attribute_7   208 non-null    float64
 7   attribute_8   208 non-null    float64
 8   attribute_9   208 non-null    float64
 9   attribute_10  208 non-null    float64
 10  attribute_11  208 non-null    float64
 11  attribute_12  208 non-null    float64
 12  attribute_13  208 non-null    float64
 13  attribute_14  208 non-null    float64
 14  attribute_15  208 non-null    float64
 15  attribute_16  208 non-null    float64
 16  attribute_17  208 non-null    float64
 17  attribute_18  208 non-null    float64
 18  attribute_19  208 non-null    

In the above cell output we see that there is "Class" column which is categorical and "No null value column"

# Now lets seperate the featutres and target variable

In [6]:
# Dependent variables or features
inputs = df.drop(['Class'],axis='columns')
inputs.head()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0       0.0200       0.0371       0.0428       0.0207       0.0954   
1       0.0453       0.0523       0.0843       0.0689       0.1183   
2       0.0262       0.0582       0.1099       0.1083       0.0974   
3       0.0100       0.0171       0.0623       0.0205       0.0205   
4       0.0762       0.0666       0.0481       0.0394       0.0590   

   attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0       0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1       0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2       0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3       0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4       0.0649       0.1209       0.2467       0.3564        0.4459  ...   

   attribute_51  attribute_52  attribute_53  attribute_54  attribute_55  \
0        0.0232        0.0027        0.0065        0.0159        0.0072   
1        0.0125        0.0084        0.0089        0.0048        0.0094   
2        0.0033        0.0232        0.0166        0.0095        0.0180   
3        0.0241        0.0121        0.0036        0.0150        0.0085   
4        0.0156        0.0031        0.0054        0.0105        0.0110   

   attribute_56  attribute_57  attribute_58  attribute_59  attribute_60  
0        0.0167        0.0180        0.0084        0.0090        0.0032  
1        0.0191        0.0140        0.0049        0.0052        0.0044  
2        0.0244        0.0316        0.0164        0.0095        0.0078  
3        0.0073        0.0050        0.0044        0.0040        0.0117  
4        0.0015        0.0072        0.0048        0.0107        0.0094  

[5 rows x 60 columns]

In [7]:
# Independent Variable or target
target = df['Class']
target.head()

0    Rock
1    Rock
2    Rock
3    Rock
4    Rock
Name: Class, dtype: object

# Building the Model using Naive_Bayes

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2 ,random_state=42)
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [9]:
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
X_test[:10]

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
161       0.0305       0.0363       0.0214       0.0227       0.0456   
15        0.0298       0.0615       0.0650       0.0921       0.1615   
73        0.0139       0.0222       0.0089       0.0108       0.0215   
96        0.0181       0.0146       0.0026       0.0141       0.0421   
166       0.0411       0.0277       0.0604       0.0525       0.0489   
9         0.0164       0.0173       0.0347       0.0070       0.0187   
100       0.0629       0.1065       0.1526       0.1229       0.1437   
135       0.0094       0.0611       0.1136       0.1203       0.0403   
18        0.0270       0.0092       0.0145       0.0278       0.0412   
148       0.0712       0.0901       0.1276       0.1497       0.1284   

     attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
161       0.0665       0.0939       0.0972       0.2535        0.3127  ...   
15        0.2294       0.2176       0.2033       0.1459        0.0852  ...   
73        0.0136       0.0659       0.0954       0.0786        0.1015  ...   
96        0.0473       0.0361       0.0741       0.1398        0.1045  ...   
166       0.0385       0.0611       0.1117       0.1237        0.2300  ...   
9         0.0671       0.1056       0.0697       0.0962        0.0251  ...   
100       0.1190       0.0884       0.0907       0.2107        0.3597  ...   
135       0.1227       0.2495       0.4566       0.6587        0.5079  ...   
18        0.0757       0.1026       0.1138       0.0794        0.1520  ...   
148       0.1165       0.1285       0.1684       0.1830        0.2127  ...   

     attribute_51  attribute_52  attribute_53  attribute_54  attribute_55  \
161        0.0271        0.0200        0.0070        0.0070        0.0086   
15         0.0154        0.0031        0.0153        0.0071        0.0212   
73         0.0024        0.0062        0.0072        0.0113        0.0012   
96         0.0076        0.0223        0.0255        0.0145        0.0233   
166        0.0181        0.0217        0.0038        0.0019        0.0065   
9          0.0118        0.0090        0.0223        0.0179        0.0084   
100        0.0257        0.0089        0.0262        0.0108        0.0138   
135        0.0480        0.0234        0.0175        0.0352        0.0158   
18         0.0045        0.0084        0.0010        0.0018        0.0068   
148        0.0154        0.0154        0.0156        0.0054        0.0030   

     attribute_56  attribute_57  attribute_58  attribute_59  attribute_60  
161        0.0089        0.0074        0.0042        0.0055        0.0021  
15         0.0076        0.0152        0.0049        0.0200        0.0073  
73         0.0022        0.0025        0.0059        0.0039        0.0048  
96         0.0041        0.0018        0.0048        0.0089        0.0085  
166        0.0132        0.0108        0.0050        0.0085        0.0044  
9          0.0068        0.0032        0.0035        0.0056        0.0040  
100        0.0187        0.0230        0.0057        0.0113        0.0131  
135        0.0326        0.0201        0.0168        0.0245        0.0154  
18         0.0039        0.0120        0.0132        0.0070        0.0088  
148        0.0048        0.0087        0.0101        0.0095        0.0068  

[10 rows x 60 columns]

In [11]:
y_test[:10]

161    Mine
15     Rock
73     Rock
96     Rock
166    Mine
9      Rock
100    Mine
135    Mine
18     Rock
148    Mine
Name: Class, dtype: object

In [12]:
model.predict(X_test[:10])

array(['Mine', 'Rock', 'Rock', 'Rock', 'Mine', 'Rock', 'Mine', 'Mine',
       'Rock', 'Mine'], dtype='<U4')

In [13]:
model.predict_proba(X_test[:10])

array([[1.00000000e+00, 6.15094388e-11],
       [2.50927830e-02, 9.74907217e-01],
       [2.30637078e-06, 9.99997694e-01],
       [3.99698933e-05, 9.99960030e-01],
       [9.99888504e-01, 1.11495964e-04],
       [4.31157359e-05, 9.99956884e-01],
       [9.99967896e-01, 3.21038903e-05],
       [1.00000000e+00, 2.79819028e-15],
       [1.89534557e-06, 9.99998105e-01],
       [9.99958844e-01, 4.11564833e-05]])

In [14]:
model.score(X_test,y_test)

0.7380952380952381

We see that we have the accuracy of 74% approx which isn't that good! So lets try "Logistic Regressioin"

# Logistic_Regression

In [15]:
#Logistic Regression
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [16]:
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2,random_state=42)

In [17]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)

In [18]:
y_pred = LR.predict(X_test)
print(confusion_matrix(y_test,y_pred))

[[26  0]
 [10  6]]


In [19]:
print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))

Accuracy:  0.7619047619047619


Again from Logistic Regression we get an accuracy of 76%, which can be improved so lets try "SVM"

# Support Vector Machine

In [20]:
#Support Vector Machine
from sklearn.svm import SVC

In [21]:
svc = SVC(random_state=42,probability=True)
svc.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [22]:
svc.score(X_test,y_test)

0.8333333333333334

In [23]:
y_pred = svc.predict(X_test)
print(confusion_matrix(y_test,y_pred))

[[21  5]
 [ 2 14]]


In [24]:
print("Accuracy: ",metrics.accuracy_score(y_test,y_pred)*100,'%')

Accuracy:  83.33333333333334 %
